### ISSUE TITLE
Quizzes start with first question filled out already

### ISSUE THREAD

**Issue by coryjbergquist** [learn-co-curriculum/case-statements-quiz#10]
Sometimes the quizzes will have the first question automatically guessed as the first option. Refreshing the page seems to reset the quiz so it can be started correctly.

**Comment by cjbrock** [comment]
Thanks @coryjbergquist! This is a known issue on Learn that is intermittent and can't seem to be reproduced consistently enough currently for us to nail it down, but it's on our list and we're working on it. Thank you for taking your time to make Learn a better place. 

// <3 Corinna
