### ISSUE TITLE
2nd question is confusing with prior study material

### ISSUE THREAD

**Issue by SnowboardTechie** [learn-co-curriculum/case-statements-quiz#4]
The 2nd question "Of the follow 2 examples, which uses the case statement the best?"
The test stated the correct answer was the case setup using when/then, nothing in the previous material that was teaching case statements talks about when/then being a way you can setup a case statement.

**Comment by AnnJohn** [comment]
thanks @SnowboardTechie. We added a note to students to actually look up this info. We want students to slowly be able to google and look up info on their own, but we should have stated this expectation when the curriculum is this early on so we modified the readme. thanks!
