### ISSUE TITLE
Quiz #2

### ISSUE THREAD

**Issue by Joeycho** [learn-co-curriculum/case-statements-quiz#7]
Hi,

I'm wondering why the second example is the best case statement of the two.

As I choose the answer as the first one in quiz #1, I guess there is no slightly implicated meaning, like "welcome back ,#{name}" or "Hi #{name}" should be applied for everyone. Is this the reason to choose the second one as the best case statement? If it is, it might be better to edit the first Quiz to make it better :)

I'm wondering what is the teaching point in Quiz 2.

Plus, Is there **then** syntax in the case statement in Ruby? On my research, it's not common obviously.

**Comment by sgharms** [comment]
I agree! This was confusing to me. I don't think that one is better than the other as a `case` statement. I'm integrating a change into this quiz, thanks!
