### ISSUE TITLE
Quiz questions are answered

### ISSUE THREAD

**Issue by DiloromA** [learn-co-curriculum/case-statements-quiz#9]
Every time I start  quiz pages, some or all questions are selected with correct answers. They go blank after I refresh the page.

**Comment by drakeltheryuujin** [comment]
Hi @Dillorom,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If this is still an issue and you can provide further detail about the steps required to reproduce the issue, I'd be happy to take a second look!

As always, thanks for contributing! 💙
